# Generated by Django 5.1.6 on 2026-04-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_media_page_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='dois_fatores_segredo',
            new_name='two_factor_secret',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dois_fatores_ativado',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='Autenticação de Dois Fatores'),
        ),
    ]
