# Generated by Django 5.1.6 on 2026-04-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_rename_dois_fatores_segredo_userprofile_two_factor_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'Texto Curto'), ('TEXTAREA', 'Texto Longo'), ('NUMBER', 'Número'), ('BOOLEAN', 'Sim/Não'), ('EMAIL', 'E-mail'), ('URL', 'Link (URL)'), ('DATE', 'Data')], default='TEXT', max_length=20, verbose_name='Tipo de Campo'),
        ),
    ]
