# Generated by Django 5.1.6 on 2026-04-10 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_systemsetting_field_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Secretaria')),
                ('slug', models.SlugField(unique=True)),
                ('icone', models.CharField(default='bi-building', max_length=50, verbose_name='Ícone Bootstrap')),
                ('cor', models.CharField(default='#0d6efd', max_length=20, verbose_name='Cor de Identificação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='admin_panel.secretaria'),
        ),
    ]
