# Generated by Django 5.1.6 on 2026-05-28 05:56

from django.db import migrations
from django.utils.text import slugify

def normalize_secretarias(apps, schema_editor):
    Secretaria = apps.get_model('admin_panel', 'Secretaria')
    Contract = apps.get_model('contratos', 'Contract')
    UserProfile = apps.get_model('admin_panel', 'UserProfile')
    ControleMensal = apps.get_model('contratos', 'ControleMensal')
    
    MAPPING = {
        "Gabinete do Prefeita": "GABINETE",
        "Secretaria de Administração": "ADMINISTRAÇÃO",
        "Secretaria de Assistência Social": "ASSISTENCIA SOCIAL",
        "Secretaria de Educação": "EDUCAÇÃO",
        "Secretaria de Fazenda": "FAZENDA",
        "Secretaria de Obras": "OBRAS",
        "Secretaria de Saúde": "SAÚDE",
        "Procuradoria Geral": "PROCURADORIA GERAL",
    }

    CORRECT_SECRETARIAS = [
        "ADMINISTRAÇÃO", "AGRICULTURA", "ASSISTENCIA SOCIAL", "COMUNICAÇÃO", 
        "CONTROLE INTERNO", "CULTURA", "DESENVOLVIMENTO", "EDUCAÇÃO", 
        "ESPORTE", "FAZENDA", "GABINETE", "MEIO AMBIENTE", "OBRAS", 
        "PESCA", "PROCURADORIA GERAL", "SAÚDE", "SEGURANÇA PÚBLICA", 
        "SERVIÇO PUBLICO", "SJB PREV"
    ]

    print("\n--- INÍCIO DA NORMALIZAÇÃO DE SECRETARIAS ---")
    
    # Counters for logging
    count_created = 0
    count_updated_contracts = 0
    count_updated_users = 0
    count_updated_mensal = 0
    count_deleted = 0
    count_found_old = 0

    # 1. Ensure all correct secretarias exist
    for name in CORRECT_SECRETARIAS:
        slug = slugify(name)
        sec = Secretaria.objects.filter(slug=slug).first()
        if not sec:
            # Create if it doesn't exist
            Secretaria.objects.create(nome=name, slug=slug)
            count_created += 1
        else:
            if sec.nome != name:
                sec.nome = name
                sec.save()

    # 2. Map old to new
    for old_name, new_name in MAPPING.items():
        # find old secretaria
        old_sec = Secretaria.objects.filter(nome=old_name).first()
        if old_sec:
            count_found_old += 1
            new_sec = Secretaria.objects.filter(nome=new_name).first()
            if new_sec and old_sec.id != new_sec.id:
                # Update references
                c_upd = Contract.objects.filter(secretaria=old_sec).update(secretaria=new_sec)
                count_updated_contracts += c_upd
                
                u_upd = UserProfile.objects.filter(secretaria=old_sec).update(secretaria=new_sec)
                count_updated_users += u_upd
                
                m_upd = ControleMensal.objects.filter(secretaria=old_sec).update(secretaria=new_sec)
                count_updated_mensal += m_upd
                
                # Verify if all relationships were updated before deleting
                rem_c = Contract.objects.filter(secretaria=old_sec).count()
                rem_u = UserProfile.objects.filter(secretaria=old_sec).count()
                rem_m = ControleMensal.objects.filter(secretaria=old_sec).count()
                
                if rem_c == 0 and rem_u == 0 and rem_m == 0:
                    old_sec.delete()
                    count_deleted += 1
                else:
                    print(f"AVISO: Não foi possível deletar '{old_name}' pois ainda possui vínculos ({rem_c} contratos, {rem_u} usuários, {rem_m} controles).")

    # 3. Ensure contract ID 3 is GABINETE
    gabinete = Secretaria.objects.filter(nome="GABINETE").first()
    if gabinete:
        contract_3 = Contract.objects.filter(id=3).first()
        if contract_3 and contract_3.secretaria_id != gabinete.id:
            contract_3.secretaria = gabinete
            contract_3.save()
            print("INFO: Contrato ID 3 atualizado forçadamente para GABINETE.")
            
    print(f"Secretarias antigas encontradas: {count_found_old}")
    print(f"Novas secretarias criadas: {count_created}")
    print(f"Contratos atualizados: {count_updated_contracts}")
    print(f"Usuários atualizados: {count_updated_users}")
    print(f"Registros mensais atualizados: {count_updated_mensal}")
    print(f"Secretarias obsoletas removidas: {count_deleted}")
    print("--- FIM DA NORMALIZAÇÃO DE SECRETARIAS ---\n")

def reverse_normalize(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_secretaria_userprofile_secretaria'),
        ('contratos', '0023_controlemensal'),  # Needs this to modify Contract correctly
    ]

    operations = [
        migrations.RunPython(normalize_secretarias, reverse_normalize),
    ]
