# Generated by Django 5.1.6 on 2026-02-25 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True)),
                ('partes_envolvidas', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('encerrado', 'Encerrado')], max_length=20)),
                ('descricao', models.TextField()),
                ('dias_restantes', models.IntegerField(default=0)),
                ('alerta', models.CharField(choices=[('normal', 'Normal'), ('amarelo', 'Amarelo'), ('laranja', 'Laranja'), ('vermelho', 'Vermelho'), ('vencido', 'Vencido')], default='normal', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContractHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
                ('alteracoes', models.JSONField()),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='contratos.contract')),
            ],
        ),
    ]
