# Generated by Django 5.1.6 on 2026-02-25 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='partes_envolvidas',
        ),
    ]
