# Generated by Django 5.1.6 on 2026-02-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_remove_contract_partes_envolvidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='numero_ficha',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Ficha'),
        ),
        migrations.AddField(
            model_name='contract',
            name='numero_nota_empenho',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Nota de Empenho'),
        ),
        migrations.AddField(
            model_name='contract',
            name='numero_pregao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Pregão'),
        ),
        migrations.AddField(
            model_name='contract',
            name='numero_protocolo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Protocolo'),
        ),
        migrations.AddField(
            model_name='contract',
            name='processo_administrativo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Processo Administrativo'),
        ),
        migrations.AddField(
            model_name='contract',
            name='quantidade',
            field=models.IntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='contract',
            name='secretario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Secretário(a)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='unidade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='contract',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Unitário'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='data_vencimento',
            field=models.DateField(verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='descricao',
            field=models.TextField(verbose_name='Tipo de Item / Descrição'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='numero_contrato',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número do Contrato'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('encerrado', 'Encerrado')], default='ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total'),
        ),
    ]
