# Generated by Django 5.1.6 on 2026-02-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_contract_numero_ficha_contract_numero_nota_empenho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='vigencia',
            field=models.IntegerField(default=12, verbose_name='Vigência (meses)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='data_vencimento',
            field=models.DateField(blank=True, verbose_name='Data de Vencimento'),
        ),
    ]
