# Generated by Django 5.1.6 on 2026-02-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_contract_vigencia_alter_contract_data_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='contratos/', verbose_name='Arquivo do Contrato'),
        ),
    ]
