# Generated by Django 5.1.6 on 2026-02-26 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_contract_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Tipo de Item / Descrição'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='quantidade',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Valor Unitário'),
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição do Item')),
                ('unidade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidade')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contratos.contract')),
            ],
        ),
    ]
