# Generated by Django 5.1.6 on 2026-02-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_alter_contract_descricao_alter_contract_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='empresa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='contract',
            name='objeto',
            field=models.TextField(blank=True, null=True, verbose_name='Objeto do Contrato'),
        ),
    ]
