# Generated by Django 5.1.6 on 2026-02-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_contract_empresa_contract_objeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='tipo_cobranca',
            field=models.CharField(choices=[('UNIDADE', 'Unidade'), ('MENSAL', 'Mensal')], default='UNIDADE', max_length=10, verbose_name='Tipo de Cobrança'),
        ),
    ]
