# Generated by Django 5.1.6 on 2026-02-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_contractitem_tipo_cobranca'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='quantidade_meses',
            field=models.IntegerField(blank=True, default=12, null=True, verbose_name='Meses'),
        ),
    ]
