# Generated by Django 5.1.6 on 2026-02-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_contractitem_quantidade_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='caixa_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Caixa Atual'),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='data_viagem',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Viagem'),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Desconto'),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='taxa_servico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Taxa de Serviço'),
        ),
    ]
