# Generated by Django 5.1.6 on 2026-02-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_contract_caixa_atual_contractitem_data_viagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='caixa_atual',
        ),
        migrations.AddField(
            model_name='contractitem',
            name='caixa_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Caixa Atual'),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='tipo_item',
            field=models.CharField(choices=[('SERVICO', 'Serviço/Produto'), ('PASSAGEM', 'Passagem Aérea')], default='SERVICO', max_length=10, verbose_name='Tipo de Item'),
        ),
    ]
