# Generated by Django 5.1.6 on 2026-02-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_remove_contract_caixa_atual_contractitem_caixa_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data Final'),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
    ]
