# Generated by Django 5.1.6 on 2026-02-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0012_contractitem_data_fim_contractitem_data_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='valor_unitario',
        ),
        migrations.RemoveField(
            model_name='contractitem',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='contractitem',
            name='data_inicio',
        ),
    ]
