# Generated by Django 5.1.6 on 2026-02-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0013_remove_contract_descricao_remove_contract_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='localidade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Localidade'),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='periodo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='proprietario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Proprietário'),
        ),
        migrations.AlterField(
            model_name='contractitem',
            name='tipo_item',
            field=models.CharField(choices=[('SERVICO', 'Serviço/Produto'), ('PASSAGEM', 'Passagem Aérea'), ('ALUGUEL', 'Aluguel')], default='SERVICO', max_length=10, verbose_name='Tipo de Item'),
        ),
    ]
