# Generated by Django 5.1.6 on 2026-02-26 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0014_contractitem_cpf_contractitem_localidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractitem',
            name='periodo',
        ),
    ]
