# Generated by Django 5.1.6 on 2026-02-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0015_remove_contractitem_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractitem',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Desconto (R$)'),
        ),
        migrations.AlterField(
            model_name='contractitem',
            name='taxa_servico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Taxa de Serviço (R$)'),
        ),
    ]
