# Generated by Django 5.1.6 on 2026-02-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0017_alter_contractitem_desconto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='responsavel',
            field=models.CharField(max_length=255, verbose_name='Responsável'),
        ),
    ]
