# Generated by Django 5.1.6 on 2026-04-10 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_secretaria_userprofile_secretaria'),
        ('contratos', '0018_alter_contract_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='admin_panel.secretaria', verbose_name='Secretaria Responsável'),
        ),
    ]
