# Generated by Django 5.1.6 on 2026-04-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0020_contract_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracthistory',
            name='acao',
            field=models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('STATUS', 'Mudança de Status'), ('ALERTA', 'Mudança de Alerta')], default='UPDATE', max_length=20),
        ),
        migrations.AddField(
            model_name='contracthistory',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contracthistory',
            name='alteracoes',
            field=models.JSONField(default=dict),
        ),
    ]
