# Generated by Django 5.1.6 on 2026-05-14 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0021_contracthistory_acao_contracthistory_descricao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='renovacao_automatica',
            field=models.BooleanField(default=False, verbose_name='Renovação Automática'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('encerrado', 'Encerrado'), ('vencendo', 'Próximo do Vencimento'), ('renovacao', 'Em Renovação'), ('renovado', 'Renovado'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='ativo', max_length=20),
        ),
        migrations.CreateModel(
            name='ContractNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=255)),
                ('nivel', models.CharField(choices=[('INFO', 'Informação'), ('WARNING', 'Aviso'), ('CRITICAL', 'Crítico')], default='INFO', max_length=10)),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='contratos.contract')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ContractRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_renovacao', models.DateTimeField(auto_now_add=True)),
                ('vencimento_anterior', models.DateField()),
                ('vencimento_novo', models.DateField()),
                ('valor_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_novo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_renovacao', models.CharField(choices=[('ADITIVO', 'Termo Aditivo'), ('RENOVACAO', 'Renovação'), ('PRORROGACAO', 'Prorrogação')], max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='renovacoes/')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovacoes', to='contratos.contract')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovacoes_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Renovação de Contrato',
                'verbose_name_plural': 'Renovações de Contrato',
                'ordering': ['-data_renovacao'],
            },
        ),
    ]
