# Generated by Django 5.1.6 on 2026-05-27 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_secretaria_userprofile_secretaria'),
        ('contratos', '0022_contract_renovacao_automatica_alter_contract_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_mes', models.IntegerField(verbose_name='Mês de Referência')),
                ('referencia_ano', models.IntegerField(verbose_name='Ano de Referência')),
                ('valor_previsto', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Previsto (R$)')),
                ('valor_utilizado', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Utilizado (R$)')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Saldo (R$)')),
                ('percentual_executado', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='% Executado')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='controle_mensal/', verbose_name='Comprovante / Anexo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controle_mensal', to='contratos.contract', verbose_name='Contrato')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controle_mensal_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controle_mensal', to='admin_panel.secretaria', verbose_name='Secretaria')),
            ],
            options={
                'verbose_name': 'Controle Mensal',
                'verbose_name_plural': 'Controles Mensais',
                'ordering': ['referencia_ano', 'referencia_mes'],
                'indexes': [models.Index(fields=['contrato'], name='cm_contrato_idx'), models.Index(fields=['secretaria'], name='cm_secretaria_idx'), models.Index(fields=['referencia_mes'], name='cm_mes_idx'), models.Index(fields=['referencia_ano'], name='cm_ano_idx'), models.Index(fields=['status'], name='cm_status_idx')],
                'unique_together': {('contrato', 'referencia_mes', 'referencia_ano')},
            },
        ),
    ]
